### ISSUE TITLE
High Level Analysis of SoloConnect

### ISSUE THREAD

**Issue by kravisankaran** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#1]
The team will:
- [x] Design SoloConnect's high level context diagram 
- [x] Present the epics described in the high level context diagram
- [x] Publish the Wiki
